app = 'evoagentx-server'
primary_region = 'sea'

[env]
  LOG_LEVEL = 'warning'
  SUPPRESS_WARNINGS = 'true'
  VERBOSE_STARTUP = 'false'

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  interval = '600s'
  timeout = '100s'
  grace_period = '30s'
  method = 'GET'
  path = '/health'
  protocol = 'http'

[http_service.http_options]
  response.headers."Access-Control-Allow-Origin" =  "https://*.create-x.studio, https://*.csb.app"
  response.headers."Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
  response.headers."Access-Control-Allow-Headers" = "eax_access_token"
  response.headers."Access-Control-Allow-Credentials" = "true"
  response.headers."Access-Control-Max-Age" = "3600"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1