# this file contains the description of the parameters for the Volcengine TTS service, including various voice types

PARAM_VOICE_TYPE_DESC = """
The type of the voice to use. Below are the supported voice types, [] Symbol labels are used to indicate their purpose, the format of each item is (voice_type_name, voice_type_unique_code, voice_type_supported_languages, supported_emotions,if_support_MIX):
Pay attention that some voice types do not support multiple emotions and MIX mode.
[多情感]
("冷酷哥哥（多情感）","zh_male_lengkugege_emo_v2_mars_bigtts",["中文"],["生气","冷漠","恐惧","开心","厌恶","中性","悲伤","沮丧"],false)
("甜心小美（多情感）","zh_female_tianxinxiaomei_emo_v2_mars_bigtts",["中文"],["悲伤","恐惧","厌恶","中性"],false)
("高冷御姐（多情感）","zh_female_gaolengyujie_emo_v2_mars_bigtts",["中文"],["开心","悲伤","生气","惊讶","恐惧","厌恶","激动","冷漠","中性"],false)
("傲娇霸总（多情感）","zh_male_aojiaobazong_emo_v2_mars_bigtts",["中文"],["中性","开心","愤怒","厌恶"],false)
("邻居阿姨（多情感）","zh_female_linjuayi_emo_v2_mars_bigtts",["中文"],["中性","愤怒","冷漠","沮丧","惊讶"],false)
("优柔公子（多情感）","zh_male_yourougongzi_emo_v2_mars_bigtts",["中文"],["开心","生气","恐惧","厌恶","激动","中性","沮丧"],false)
("儒雅男友（多情感）","zh_male_ruyayichen_emo_v2_mars_bigtts",["中文"],["开心","悲伤","生气","恐惧","激动","冷漠","中性"],false)
("Candice","en_female_candice_emo_v2_mars_bigtts",["美式英语"],["深情","愤怒","ASMR","对话/闲聊","兴奋","愉悦","中性","温暖"],false)
("Sylus","en_male_sylus_emo_v2_mars_bigtts",["美式英语"],["深情","愤怒","ASMR","权威","对话/闲聊","兴奋","愉悦","中性","悲伤","温暖"],false)
("深夜播客","zh_male_shenyeboke_emo_v2_mars_bigtts",["中文"],["惊讶","悲伤","中性","厌恶","开心","恐惧","激动","沮丧","冷漠","生气"],false)
[/多情感]

[教育场景]
("Tina老师","zh_female_yingyujiaoyu_mars_bigtts",["中文","英式英语"],[],true)
[/教育场景]

[通用场景]
("温柔女神","ICL_zh_female_wenrounvshen_239eff5e8ffa_tob",["中文"],[],true)
("元气甜妹","ICL_zh_female_wuxi_tob",["中文"],[],true)
("知性女声","zh_female_zhixingnvsheng_mars_bigtts",["中文"],[],true)
("阳光青年","zh_male_yangguangqingnian_moon_bigtts",["中文"],[],true)
("清爽男大","zh_male_qingshuangnanda_mars_bigtts",["中文"],[],true)
[/通用场景]

[IP仿音]
("唐僧","zh_male_tangseng_mars_bigtts",["中文"],[],true)
("猪八戒","zh_male_zhubajie_mars_bigtts",["中文"],[],true)
("直率英子","zh_female_naying_mars_bigtts",["中文"],[],true)
("女雷神","zh_female_leidian_mars_bigtts",["中文"],[],true)
[/IP仿音]

[趣味口音]
("粤语小溏","zh_female_yueyunv_mars_bigtts",["中文"],[],true)
("呆萌川妹","zh_female_daimengchuanmei_moon_bigtts",["中文"],[],true)
("北京小爷","zh_male_beijingxiaoye_moon_bigtts",["中文"],[],true)
("京腔侃爷/Harmony","zh_male_jingqiangkanye_moon_bigtts",["中文","美式英语"],[],true)
[/趣味口音]

[角色扮演]
("纯真少女","ICL_zh_female_chunzhenshaonv_e588402fb8ad_tob",["中文"],[],true)
("温柔男友","ICL_zh_male_wenrounanyou_tob",["中文"],[],true)
("霸道总裁","ICL_zh_male_badaozongcai_v1_tob",["中文"],[],true)
("病娇少年","ICL_zh_male_bingjiaoshaonian_tob",["中文"],[],true)
("邪魅御姐","ICL_zh_female_xiangliangya_v1_tob",["中文"],[],true)
("油腻大叔","ICL_zh_male_you_tob",["中文"],[],true)
[/角色扮演]

[多语种]
("Lauren", "en_female_lauren_moon_bigtts", "美式英语", [], true)
("Michael", "en_male_michael_moon_bigtts", "美式英语", [], true)
("Dave", "en_male_dave_moon_bigtts", "英式英语", [], true)
("Anna", "en_female_anna_mars_bigtts", "英式英语", [], true)
("ひかる（光）", "multi_zh_male_youyoujunzi_moon_bigtts", "日语", [], false)
("つき（月）", "multi_female_maomao_conversation_wvae_bigtts", "日语", [], false)
("Ethan", "ICL_en_male_aussie_v1_tob", "澳洲英语", [], true)
("Sarah", "en_female_sarah_mars_bigtts", "澳洲英语", [], true)
("Diana", "multi_female_maomao_conversation_wvae_bigtts", "西语", [], false)
("Lucía", "multi_male_M100_conversation_wvae_bigtts", "西语", [], false)
[/多语种]

[客服场景]
("理性圆子", "ICL_zh_female_lixingyuanzi_cs_tob", "中文", [], true)
("清晰小雪", "ICL_zh_female_qingxixiaoxue_cs_tob", "中文", [], true)
("爽朗小阳", "ICL_zh_male_shuanglangxiaoyang_cs_tob", "中文", [], true)
("暖阳女声", "zh_female_kefunvsheng_mars_bigtts", "中文", [], true)
[/客服场景]

[视频配音]
("悠悠君子", "zh_male_M100_conversation_wvae_bigtts", "中文", [], true)
("广告解说", "zh_male_chunhui_mars_bigtts", "中文", [], true)
("猴哥", "zh_male_sunwukong_mars_bigtts", "中文", [], true)
("熊二", "zh_male_xionger_mars_bigtts", "中文", [], true)
("磁性解说男声/Morgan", "zh_male_jieshuonansheng_mars_bigtts", "中文,美式英语", [], true)
[/视频配音]

[有声阅读]
("悬疑解说", "zh_male_changtianyi_mars_bigtts", "中文", [], true)
("儒雅青年", "zh_male_ruyaqingnian_mars_bigtts", "中文", [], true)
("温柔淑女", "zh_female_wenroushunv_mars_bigtts", "中文", [], true)
("霸气青叔", "zh_male_baqiqingshu_mars_bigtts", "中文", [], true)
[/有声阅读]
"""

PARAM_EMOTION_DESC = """
unique emotion codes to identify the emotion of the voice type. Pay attention that some voice types do not support multiple emotions and MIX mode.
between the brackets are the emotion parameters:
中文音色：​开心（happy），悲伤（sad），生气（angry），惊讶（surprised），恐惧（fear），厌恶（hate），激动（excited），冷漠（coldness），中性（neutral），沮丧（depressed），撒娇（lovey-dovey），害羞（shy），安慰鼓励（comfort），咆哮/焦急（tension），温柔（tender），讲故事 / 自然讲述（storytelling），情感电台（radio），磁性（magnetic），广告营销（advertising），气泡音（vocal - fry），低语 (ASMR)，新闻播报（news），娱乐八卦（entertainment），方言（dialect）
英文音色：​中性（neutral），愉悦（happy），愤怒（angry），悲伤（sad），兴奋（excited），对话 / 闲聊（chat），低语 (ASMR)，温暖（warm），深情（affectionate），权威（authoritative）
"""

ORIGINAL_VOICE_TYPE_DESC = """
[多情感]
("冷酷哥哥（多情感）","zh_male_lengkugege_emo_v2_mars_bigtts",["中文"],["生气","冷漠","恐惧","开心","厌恶","中性","悲伤","沮丧"],false)
("甜心小美（多情感）","zh_female_tianxinxiaomei_emo_v2_mars_bigtts",["中文"],["悲伤","恐惧","厌恶","中性"],false)
("高冷御姐（多情感）","zh_female_gaolengyujie_emo_v2_mars_bigtts",["中文"],["开心","悲伤","生气","惊讶","恐惧","厌恶","激动","冷漠","中性"],false)
("傲娇霸总（多情感）","zh_male_aojiaobazong_emo_v2_mars_bigtts",["中文"],["中性","开心","愤怒","厌恶"],false)
("广州德哥（多情感）","zh_male_guangzhoudege_emo_mars_bigtts",["中文"],["生气","恐惧","中性"],true)
("京腔侃爷（多情感）","zh_male_jingqiangkanye_emo_mars_bigtts",["中文"],["开心","生气","惊讶","厌恶","中性"],true)
("邻居阿姨（多情感）","zh_female_linjuayi_emo_v2_mars_bigtts",["中文"],["中性","愤怒","冷漠","沮丧","惊讶"],false)
("优柔公子（多情感）","zh_male_yourougongzi_emo_v2_mars_bigtts",["中文"],["开心","生气","恐惧","厌恶","激动","中性","沮丧"],false)
("儒雅男友（多情感）","zh_male_ruyayichen_emo_v2_mars_bigtts",["中文"],["开心","悲伤","生气","恐惧","激动","冷漠","中性"],false)
("俊朗男友（多情感）","zh_male_junlangnanyou_emo_v2_mars_bigtts",["中文"],["开心","悲伤","生气","惊讶","恐惧","中性"],false)
("Candice","en_female_candice_emo_v2_mars_bigtts",["美式英语"],["深情","愤怒","ASMR","对话/闲聊","兴奋","愉悦","中性","温暖"],false)
("Serena","en_female_skye_emo_v2_mars_bigtts",["美式英语"],["深情","愤怒","ASMR","对话/闲聊","兴奋","愉悦","中性","悲伤","温暖"],false)
("Glen","en_male_glen_emo_v2_mars_bigtts",["美式英语"],["深情","愤怒","ASMR","对话/闲聊","兴奋","愉悦","中性","悲伤","温暖"],false)
("Sylus","en_male_sylus_emo_v2_mars_bigtts",["美式英语"],["深情","愤怒","ASMR","权威","对话/闲聊","兴奋","愉悦","中性","悲伤","温暖"],false)
("深夜播客","zh_male_shenyeboke_emo_v2_mars_bigtts",["中文"],["惊讶","悲伤","中性","厌恶","开心","恐惧","激动","沮丧","冷漠","生气"],false)
[/多情感]

[教育场景]
("Tina老师","zh_female_yingyujiaoyu_mars_bigtts",["中文","英式英语"],[],true)
[/教育场景]

[通用场景]
("温柔女神","ICL_zh_female_wenrounvshen_239eff5e8ffa_tob",["中文"],[],true)
("Vivi","zh_female_vv_mars_bigtts",["中文"],[],true)
("亲切女声","zh_female_qinqienvsheng_moon_bigtts",["中文"],[],true)
("机灵小伙","ICL_zh_male_shenmi_v1_tob",["中文"],[],true)
("元气甜妹","ICL_zh_female_wuxi_tob",["中文"],[],true)
("知心姐姐","ICL_zh_female_wenyinvsheng_v1_tob",["中文"],[],true)
("阳光阿辰","zh_male_qingyiyuxuan_mars_bigtts",["中文"],[],true)
("快乐小东","zh_male_xudong_conversation_wvae_bigtts",["中文"],[],true)
("冷酷哥哥","ICL_zh_male_lengkugege_v1_tob",["中文"],[],true)
("纯澈女生","ICL_zh_female_feicui_v1_tob",["中文"],[],true)
("初恋女友","ICL_zh_female_yuxin_v1_tob",["中文"],[],true)
("贴心闺蜜","ICL_zh_female_xnx_tob",["中文"],[],true)
("温柔白月光","ICL_zh_female_yry_tob",["中文"],[],true)
("炀炀","ICL_zh_male_BV705_streaming_cs_tob",["中文"],[],true)
("开朗学长","en_male_jason_conversation_wvae_bigtts",["中文"],[],true)
("魅力苏菲","zh_female_sophie_conversation_wvae_bigtts",["中文"],[],true)
("贴心妹妹","ICL_zh_female_yilin_tob",["中文"],[],true)
("甜美桃子","zh_female_tianmeitaozi_mars_bigtts",["中文"],[],true)
("清新女声","zh_female_qingxinnvsheng_mars_bigtts",["中文"],[],true)
("知性女声","zh_female_zhixingnvsheng_mars_bigtts",["中文"],[],true)
("清爽男大","zh_male_qingshuangnanda_mars_bigtts",["中文"],[],true)
("邻家女孩","zh_female_linjianvhai_moon_bigtts",["中文"],[],true)
("渊博小叔","zh_male_yuanboxiaoshu_moon_bigtts",["中文"],[],true)
("阳光青年","zh_male_yangguangqingnian_moon_bigtts",["中文"],[],true)
("甜美小源","zh_female_tianmeixiaoyuan_moon_bigtts",["中文"],[],true)
("清澈梓梓","zh_female_qingchezizi_moon_bigtts",["中文"],[],true)
("解说小明","zh_male_jieshuoxiaoming_moon_bigtts",["中文"],[],true)
("开朗姐姐","zh_female_kailangjiejie_moon_bigtts",["中文"],[],true)
("邻家男孩","zh_male_linjiananhai_moon_bigtts",["中文"],[],true)
("甜美悦悦","zh_female_tianmeiyueyue_moon_bigtts",["中文"],[],true)
("心灵鸡汤","zh_female_xinlingjitang_moon_bigtts",["中文"],[],true)
("知性温婉","ICL_zh_female_zhixingwenwan_tob",["中文"],[],true)
("暖心体贴","ICL_zh_male_nuanxintitie_tob",["中文"],[],true)
("开朗轻快","ICL_zh_male_kailangqingkuai_tob",["中文"],[],true)
("活泼爽朗","ICL_zh_male_huoposhuanglang_tob",["中文"],[],true)
("率真小伙","ICL_zh_male_shuaizhenxiaohuo_tob",["中文"],[],true)
("温柔小哥","zh_male_wenrouxiaoge_mars_bigtts",["中文"],[],true)
("灿灿/Shiny","zh_female_cancan_mars_bigtts",["中文","美式英语"],[],true)
("爽快思思/Skye","zh_female_shuangkuaisisi_moon_bigtts",["中文","美式英语"],[],true)
("温暖阿虎/Alvin","zh_male_wennuanahu_moon_bigtts",["中文","美式英语"],[],true)
("少年梓辛/Brayan","zh_male_shaonianzixin_moon_bigtts",["中文","美式英语"],[],true)
("温柔文雅","ICL_zh_female_wenrouwenya_tob",["中文"],[],true)
[/通用场景]

[IP仿音]
("沪普男","zh_male_hupunan_mars_bigtts",["中文"],[],true)
("鲁班七号","zh_male_lubanqihao_mars_bigtts",["中文"],[],true)
("林潇","zh_female_yangmi_mars_bigtts",["中文"],[],true)
("玲玲姐姐","zh_female_linzhiling_mars_bigtts",["中文"],[],true)
("春日部姐姐","zh_female_jiyejizi2_mars_bigtts",["中文"],[],true)
("唐僧","zh_male_tangseng_mars_bigtts",["中文"],[],true)
("庄周","zh_male_zhuangzhou_mars_bigtts",["中文"],[],true)
("猪八戒","zh_male_zhubajie_mars_bigtts",["中文"],[],true)
("感冒电音姐姐","zh_female_ganmaodianyin_mars_bigtts",["中文"],[],true)
("直率英子","zh_female_naying_mars_bigtts",["中文"],[],true)
("女雷神","zh_female_leidian_mars_bigtts",["中文"],[],true)
[/IP仿音]

[趣味口音]
("粤语小溏","zh_female_yueyunv_mars_bigtts",["中文"],[],true)
("豫州子轩","zh_male_yuzhouzixuan_moon_bigtts",["中文"],[],true)
("呆萌川妹","zh_female_daimengchuanmei_moon_bigtts",["中文"],[],true)
("广西远舟","zh_male_guangxiyuanzhou_moon_bigtts",["中文"],[],true)
("双节棍小哥","zh_male_zhoujielun_emo_v2_mars_bigtts",["中文"],[],false)
("湾湾小何","zh_female_wanwanxiaohe_moon_bigtts",["中文"],[],true)
("湾区大叔","zh_female_wanqudashu_moon_bigtts",["中文"],[],true)
("广州德哥","zh_male_guozhoudege_moon_bigtts",["中文"],[],true)
("浩宇小哥","zh_male_haoyuxiaoge_moon_bigtts",["中文"],[],true)
("北京小爷","zh_male_beijingxiaoye_moon_bigtts",["中文"],[],true)
("京腔侃爷/Harmony","zh_male_jingqiangkanye_moon_bigtts",["中文","美式英语"],[],true)
("妹坨洁儿","zh_female_meituojieer_moon_bigtts",["中文"],[],true)
[/趣味口音]

[角色扮演]
("纯真少女","ICL_zh_female_chunzhenshaonv_e588402fb8ad_tob",["中文"],[],true)
("奶气小生","ICL_zh_male_xiaonaigou_edf58cf28b8b_tob",["中文"],[],true)
("精灵向导","ICL_zh_female_jinglingxiangdao_1beb294a9e3e_tob",["中文"],[],true)
("闷油瓶小哥","ICL_zh_male_menyoupingxiaoge_ffed9fc2fee7_tob",["中文"],[],true)
("黯刃秦主","ICL_zh_male_anrenqinzhu_cd62e63dcdab_tob",["中文"],[],true)
("霸道总裁","ICL_zh_male_badaozongcai_v1_tob",["中文"],[],true)
("妩媚可人","ICL_zh_female_ganli_v1_tob",["中文"],[],true)
("邪魅御姐","ICL_zh_female_xiangliangya_v1_tob",["中文"],[],true)
("嚣张小哥","ICL_zh_male_ms_tob",["中文"],[],true)
("油腻大叔","ICL_zh_male_you_tob",["中文"],[],true)
("孤傲公子","ICL_zh_male_guaogongzi_v1_tob",["中文"],[],true)
("胡子叔叔","ICL_zh_male_huzi_v1_tob",["中文"],[],true)
("性感魅惑","ICL_zh_female_luoqing_v1_tob",["中文"],[],true)
("病弱公子","ICL_zh_male_bingruogongzi_tob",["中文"],[],true)
("邪魅女王","ICL_zh_female_bingjiao3_tob",["中文"],[],true)
("傲慢青年","ICL_zh_male_aomanqingnian_tob",["中文"],[],true)
("醋精男生","ICL_zh_male_cujingnansheng_tob",["中文"],[],true)
("爽朗少年","ICL_zh_male_shuanglangshaonian_tob",["中文"],[],true)
("撒娇男友","ICL_zh_male_sajiaonanyou_tob",["中文"],[],true)
("温柔男友","ICL_zh_male_wenrounanyou_tob",["中文"],[],true)
("温顺少年","ICL_zh_male_wenshunshaonian_tob",["中文"],[],true)
("粘人男友","ICL_zh_male_naigounanyou_tob",["中文"],[],true)
("撒娇男生","ICL_zh_male_sajiaonansheng_tob",["中文"],[],true)
("活泼男友","ICL_zh_male_huoponanyou_tob",["中文"],[],true)
("甜系男友","ICL_zh_male_tianxinanyou_tob",["中文"],[],true)
("活力青年","ICL_zh_male_huoliqingnian_tob",["中文"],[],true)
("开朗青年","ICL_zh_male_kailangqingnian_tob",["中文"],[],true)
("冷漠兄长","ICL_zh_male_lengmoxiongzhang_tob",["中文"],[],true)
("天才同桌","ICL_zh_male_tiancaitongzhuo_tob",["中文"],[],true)
("翩翩公子","ICL_zh_male_pianpiangongzi_tob",["中文"],[],true)
("懵懂青年","ICL_zh_male_mengdongqingnian_tob",["中文"],[],true)
("冷脸兄长","ICL_zh_male_lenglianxiongzhang_tob",["中文"],[],true)
("病娇少年","ICL_zh_male_bingjiaoshaonian_tob",["中文"],[],true)
("病娇男友","ICL_zh_male_bingjiaonanyou_tob",["中文"],[],true)
("病弱少年","ICL_zh_male_bingruoshaonian_tob",["中文"],[],true)
("意气少年","ICL_zh_male_yiqishaonian_tob",["中文"],[],true)
("干净少年","ICL_zh_male_ganjingshaonian_tob",["中文"],[],true)
("冷漠男友","ICL_zh_male_lengmonanyou_tob",["中文"],[],true)
("精英青年","ICL_zh_male_jingyingqingnian_tob",["中文"],[],true)
("热血少年","ICL_zh_male_rexueshaonian_tob",["中文"],[],true)
("清爽少年","ICL_zh_male_qingshuangshaonian_tob",["中文"],[],true)
("中二青年","ICL_zh_male_zhongerqingnian_tob",["中文"],[],true)
("凌云青年","ICL_zh_male_lingyunqingnian_tob",["中文"],[],true)
("自负青年","ICL_zh_male_zifuqingnian_tob",["中文"],[],true)
("不羁青年","ICL_zh_male_bujiqingnian_tob",["中文"],[],true)
("儒雅君子","ICL_zh_male_ruyajunzi_tob",["中文"],[],true)
("低音沉郁","ICL_zh_male_diyinchenyu_tob",["中文"],[],true)
("冷脸学霸","ICL_zh_male_lenglianxueba_tob",["中文"],[],true)
("儒雅总裁","ICL_zh_male_ruyazongcai_tob",["中文"],[],true)
("深沉总裁","ICL_zh_male_shenchenzongcai_tob",["中文"],[],true)
("小侯爷","ICL_zh_male_xiaohouye_tob",["中文"],[],true)
("孤高公子","ICL_zh_male_gugaogongzi_tob",["中文"],[],true)
("仗剑君子","ICL_zh_male_zhangjianjunzi_tob",["中文"],[],true)
("温润学者","ICL_zh_male_wenrunxuezhe_tob",["中文"],[],true)
("亲切青年","ICL_zh_male_qinqieqingnian_tob",["中文"],[],true)
("温柔学长","ICL_zh_male_wenrouxuezhang_tob",["中文"],[],true)
("高冷总裁","ICL_zh_male_gaolengzongcai_tob",["中文"],[],true)
("冷峻高智","ICL_zh_male_lengjungaozhi_tob",["中文"],[],true)
("孱弱少爷","ICL_zh_male_chanruoshaoye_tob",["中文"],[],true)
("自信青年","ICL_zh_male_zixinqingnian_tob",["中文"],[],true)
("青涩青年","ICL_zh_male_qingseqingnian_tob",["中文"],[],true)
("学霸同桌","ICL_zh_male_xuebatongzhuo_tob",["中文"],[],true)
("冷傲总裁","ICL_zh_male_lengaozongcai_tob",["中文"],[],true)
("元气少年","ICL_zh_male_yuanqishaonian_tob",["中文"],[],true)
("洒脱青年","ICL_zh_male_satuoqingnian_tob",["中文"],[],true)
("直率青年","ICL_zh_male_zhishuaiqingnian_tob",["中文"],[],true)
("斯文青年","ICL_zh_male_siwenqingnian_tob",["中文"],[],true)
("俊逸公子","ICL_zh_male_junyigongzi_tob",["中文"],[],true)
("仗剑侠客","ICL_zh_male_zhangjianxiake_tob",["中文"],[],true)
("机甲智能","ICL_zh_male_jijiaozhineng_tob",["中文"],[],true)
("奶气萌娃", "zh_male_naiqimengwa_mars_bigtts", "中文", [], true)
("婆婆", "zh_female_popo_mars_bigtts", "中文", [], true)
("婆婆", "zh_female_popo_mars_bigtts", "中文", [], true)
("撒娇粘人", "ICL_zh_male_sajiaonianren_tob", "中文", [], true)
("傲慢娇声", "ICL_zh_female_aomanjiaosheng_tob", "中文", [], true)
("潇洒随性", "ICL_zh_male_xiaosasuixing_tob", "中文", [], true)
("诡异神秘", "ICL_zh_male_guiyishenmi_tob", "中文", [], true)
("儒雅才俊", "ICL_zh_male_ruyacaijun_tob", "中文", [], true)
("正直青年", "ICL_zh_male_zhengzhiqingnian_tob", "中文", [], true)
("娇憨女王", "ICL_zh_female_jiaohannvwang_tob", "中文", [], true)
("病娇萌妹", "ICL_zh_female_bingjiaomengmei_tob", "中文", [], true)
("青涩小生", "ICL_zh_male_qingsenaigou_tob", "中文", [], true)
("纯真学弟", "ICL_zh_male_chunzhenxuedi_tob", "中文", [], true)
("优柔帮主", "ICL_zh_male_youroubangzhu_tob", "中文", [], true)
("优柔公子", "ICL_zh_male_yourougongzi_tob", "中文", [], true)
("调皮公主", "ICL_zh_female_tiaopigongzhu_tob", "中文", [], true)
("贴心男友", "ICL_zh_male_tiexinnanyou_tob", "中文", [], true)
("少年将军", "ICL_zh_male_shaonianjiangjun_tob", "中文", [], true)
("病娇哥哥", "ICL_zh_male_bingjiaogege_tob", "中文", [], true)
("学霸男同桌", "ICL_zh_male_xuebanantongzhuo_tob", "中文", [], true)
("幽默叔叔", "ICL_zh_male_youmoshushu_tob", "中文", [], true)
("假小子", "ICL_zh_female_jiaxiaozi_tob", "中文", [], true)
("温柔男同桌", "ICL_zh_male_wenrounantongzhuo_tob", "中文", [], true)
("幽默大爷", "ICL_zh_male_youmodaye_tob", "中文", [], true)
("枕边低语", "ICL_zh_male_asmryexiu_tob", "中文", [], true)
("神秘法师", "ICL_zh_male_shenmifashi_tob", "中文", [], true)
("娇喘女声", "zh_female_jiaochuan_mars_bigtts", "仅中文", [], true)
("开朗弟弟", "zh_male_livelybro_mars_bigtts", "仅中文", [], true)
("谄媚女声", "zh_female_flattery_mars_bigtts", "仅中文", [], true)
("冷峻上司", "ICL_zh_male_lengjunshangsi_tob", "中文", [], true)
("寡言小哥", "ICL_zh_male_xiaoge_v1_tob", "中文", [], true)
("清朗温润", "ICL_zh_male_renyuwangzi_v1_tob", "中文", [], true)
("潇洒随性", "ICL_zh_male_xiaosha_v1_tob", "中文", [], true)
("清冷矜贵", "ICL_zh_male_liyisheng_v1_tob", "中文", [], true)
("沉稳优雅", "ICL_zh_male_qinglen_v1_tob", "中文", [], true)
("清逸苏感", "ICL_zh_male_chongqingzhanzhan_v1_tob", "中文", [], true)
("温柔内敛", "ICL_zh_male_xingjiwangzi_v1_tob", "中文", [], true)
("低沉缱绻", "ICL_zh_male_sigeshiye_v1_tob", "中文", [], true)
("蓝银草魂师", "ICL_zh_male_lanyingcaohunshi_v1_tob", "中文", [], true)
("清冷高雅", "ICL_zh_female_liumengdie_v1_tob", "中文", [], true)
("甜美娇俏", "ICL_zh_female_linxueying_v1_tob", "中文", [], true)
("柔骨魂师", "ICL_zh_female_rouguhunshi_v1_tob", "中文", [], true)
("甜美活泼", "ICL_zh_female_tianmei_v1_tob", "中文", [], true)
("成熟温柔", "ICL_zh_female_chengshu_v1_tob", "中文", [], true)
("贴心闺蜜", "ICL_zh_female_xnx_v1_tob", "中文", [], true)
("温柔白月光", "ICL_zh_female_yry_v1_tob", "中文", [], true)
("高冷沉稳", "zh_male_bv139_audiobook_ummv3_bigtts", "中文", [], true)
("醋精男友", "ICL_zh_male_cujingnanyou_tob", "中文", [], true)
("风发少年", "ICL_zh_male_fengfashaonian_tob", "中文", [], true)
("磁性男嗓", "ICL_zh_male_cixingnansang_tob", "中文", [], true)
("成熟总裁", "ICL_zh_male_chengshuzongcai_tob", "中文", [], true)
("傲娇精英", "ICL_zh_male_aojiaojingying_tob", "中文", [], true)
("傲娇公子", "ICL_zh_male_aojiaogongzi_tob", "中文", [], true)
("霸道少爷", "ICL_zh_male_badaoshaoye_tob", "中文", [], true)
("腹黑公子", "ICL_zh_male_fuheigongzi_tob", "中文", [], true)
("暖心学姐", "ICL_zh_female_nuanxinxuejie_tob", "中文", [], true)
("可爱女生", "ICL_zh_female_keainvsheng_tob", "中文", [], true)
("成熟姐姐", "ICL_zh_female_chengshujiejie_tob", "中文", [], true)
("病娇姐姐", "ICL_zh_female_bingjiaojiejie_tob", "中文", [], true)
("妩媚御姐", "ICL_zh_female_wumeiyujie_tob", "中文", [], true)
("傲娇女友", "ICL_zh_female_aojiaonvyou_tob", "中文", [], true)
("贴心女友", "ICL_zh_female_tiexinnvyou_tob", "中文", [], true)
("性感御姐", "ICL_zh_female_xingganyujie_tob", "中文", [], true)
("病娇弟弟", "ICL_zh_male_bingjiaodidi_tob", "中文", [], true)
("傲慢少爷", "ICL_zh_male_aomanshaoye_tob", "中文", [], true)
("傲气凌人", "ICL_zh_male_aiqilingren_tob", "中文", [], true)
("病娇白莲", "ICL_zh_male_bingjiaobailian_tob", "中文", [], true)
[/角色扮演]

[多语种]
("Lauren", "en_female_lauren_moon_bigtts", "美式英语", [], true)
("Energetic Male II", "en_male_campaign_jamal_moon_bigtts", "美式英语", [], true)
("Gotham Hero", "en_male_chris_moon_bigtts", "美式英语", [], true)
("Flirty Female", "en_female_product_darcie_moon_bigtts", "美式英语", [], true)
("Peaceful Female", "en_female_emotional_moon_bigtts", "美式英语", [], true)
("Nara", "en_female_nara_moon_bigtts", "美式英语", [], true)
("Bruce", "en_male_bruce_moon_bigtts", "美式英语", [], true)
("Michael", "en_male_michael_moon_bigtts", "美式英语", [], true)
("Cartoon Chef", "ICL_en_male_cc_sha_v1_tob", "美式英语", [], true)
("Lucas", "zh_male_M100_conversation_wvae_bigtts", "美式英语", [], true)
("Sophie", "zh_female_sophie_conversation_wvae_bigtts", "美式英语", [], true)
("Daisy", "en_female_dacey_conversation_wvae_bigtts", "美式英语", [], true)
("Owen", "en_male_charlie_conversation_wvae_bigtts", "美式英语", [], true)
("Luna", "en_female_sarah_new_conversation_wvae_bigtts", "美式英语", [], true)
("Michael", "ICL_en_male_michael_tob", "美式英语", [], true)
("Charlie", "ICL_en_female_cc_cm_v1_tob", "美式英语", [], true)
("Big Boogie", "ICL_en_male_oogie2_tob", "美式英语", [], true)
("Frosty Man", "ICL_en_male_frosty1_tob", "美式英语", [], true)
("The Grinch", "ICL_en_male_grinch2_tob", "美式英语", [], true)
("Zayne", "ICL_en_male_zayne_tob", "美式英语", [], true)
("Jigsaw", "ICL_en_male_cc_jigsaw_tob", "美式英语", [], true)
("Chucky", "ICL_en_male_cc_chucky_tob", "美式英语", [], true)
("Clown Man", "ICL_en_male_cc_penny_v1_tob", "美式英语", [], true)
("Kevin McCallister", "ICL_en_male_kevin2_tob", "美式英语", [], true)
("Xavier", "ICL_en_male_xavier1_v1_tob", "美式英语", [], true)
("Noah", "ICL_en_male_cc_dracula_v1_tob", "美式英语", [], true)
("Adam", "en_male_adam_mars_bigtts", "美式英语", [], true)
("Amanda", "en_female_amanda_mars_bigtts", "美式英语", [], true)
("Jackson", "en_male_jackson_mars_bigtts", "美式英语", [], true)
("Delicate Girl", "en_female_daisy_moon_bigtts", "英式英语", [], true)
("Dave", "en_male_dave_moon_bigtts", "英式英语", [], true)
("Hades", "en_male_hades_moon_bigtts", "英式英语", [], true)
("Onez", "en_female_onez_moon_bigtts", "英式英语", [], true)
("Emily", "en_female_emily_mars_bigtts", "英式英语", [], true)
("Daniel", "zh_male_xudong_conversation_wvae_bigtts", "英式英语", [], true)
("Alastor", "ICL_en_male_cc_alastor_tob", "英式英语", [], true)
("Smith", "en_male_smith_mars_bigtts", "英式英语", [], true)
("Anna", "en_female_anna_mars_bigtts", "英式英语", [], true)
("Ethan", "ICL_en_male_aussie_v1_tob", "澳洲英语", [], true)
("Sarah", "en_female_sarah_mars_bigtts", "澳洲英语", [], true)
("Dryw", "en_male_dryw_mars_bigtts", "澳洲英语", [], true)
("Diana", "multi_female_maomao_conversation_wvae_bigtts", "西语", [], false)
("Lucía", "multi_male_M100_conversation_wvae_bigtts", "西语", [], false)
("Sofía", "multi_female_sophie_conversation_wvae_bigtts", "西语", [], false)
("Daníel", "multi_male_xudong_conversation_wvae_bigtts", "西语", [], false)
("ひかる（光）", "multi_zh_male_youyoujunzi_moon_bigtts", "日语", [], false)
("さとみ（智美）", "multi_female_sophie_conversation_wvae_bigtts", "日语", [], false)
("まさお（正男）", "multi_male_xudong_conversation_wvae_bigtts", "日语", [], false)
("つき（月）", "multi_female_maomao_conversation_wvae_bigtts", "日语", [], false)
("あけみ（朱美）", "multi_female_gaolengyujie_moon_bigtts", "日语", [], false)
("かずね（和音）/Javier or Álvaro", "multi_male_jingqiangkanye_moon_bigtts", "日语,西语", [], false)
("はるこ（晴子）/Esmeralda", "multi_female_shuangkuaisisi_moon_bigtts", "日语,西语", [], false)
("ひろし（広志）/Roberto", "multi_male_wanqudashu_moon_bigtts", "日语,西语", [], false)
[/多语种]

[客服场景]
("理性圆子", "ICL_zh_female_lixingyuanzi_cs_tob", "中文", [], true)
("清甜桃桃", "ICL_zh_female_qingtiantaotao_cs_tob", "中文", [], true)
("清晰小雪", "ICL_zh_female_qingxixiaoxue_cs_tob", "中文", [], true)
("清甜莓莓", "ICL_zh_female_qingtianmeimei_cs_tob", "中文", [], true)
("开朗婷婷", "ICL_zh_female_kailangtingting_cs_tob", "中文", [], true)
("清新沐沐", "ICL_zh_male_qingxinmumu_cs_tob", "中文", [], true)
("爽朗小阳", "ICL_zh_male_shuanglangxiaoyang_cs_tob", "中文", [], true)
("清新波波", "ICL_zh_male_qingxinbobo_cs_tob", "中文", [], true)
("温婉珊珊", "ICL_zh_female_wenwanshanshan_cs_tob", "中文", [], true)
("甜美小雨", "ICL_zh_female_tianmeixiaoyu_cs_tob", "中文", [], true)
("热情艾娜", "ICL_zh_female_reqingaina_cs_tob", "中文", [], true)
("甜美小橘", "ICL_zh_female_tianmeixiaoju_cs_tob", "中文", [], true)
("沉稳明仔", "ICL_zh_male_chenwenmingzai_cs_tob", "中文", [], true)
("亲切小卓", "ICL_zh_male_qinqiexiaozhuo_cs_tob", "中文", [], true)
("灵动欣欣", "ICL_zh_female_lingdongxinxin_cs_tob", "中文", [], true)
("乖巧可儿", "ICL_zh_female_guaiqiaokeer_cs_tob", "中文", [], true)
("暖心茜茜", "ICL_zh_female_nuanxinqianqian_cs_tob", "中文", [], true)
("软萌团子", "ICL_zh_female_ruanmengtuanzi_cs_tob", "中文", [], true)
("阳光洋洋", "ICL_zh_male_yangguangyangyang_cs_tob", "中文", [], true)
("软萌糖糖", "ICL_zh_female_ruanmengtangtang_cs_tob", "中文", [], true)
("秀丽倩倩", "ICL_zh_female_xiuliqianqian_cs_tob", "中文", [], true)
("开心小鸿", "ICL_zh_female_kaixinxiaohong_cs_tob", "中文", [], true)
("轻盈朵朵", "ICL_zh_female_qingyingduoduo_cs_tob", "中文", [], true)
("暖阳女声", "zh_female_kefunvsheng_mars_bigtts", "中文", [], true)
[/客服场景]

[视频配音]
("悠悠君子", "zh_male_M100_conversation_wvae_bigtts", "中文", [], true)
("文静毛毛", "zh_female_maomao_conversation_wvae_bigtts", "中文", [], true)
("倾心少女", "ICL_zh_female_qiuling_v1_tob", "中文", [], true)
("醇厚低音", "ICL_zh_male_buyan_v1_tob", "中文", [], true)
("咆哮小哥", "ICL_zh_male_BV144_paoxiaoge_v1_tob", "中文", [], true)
("和蔼奶奶", "ICL_zh_female_heainainai_tob", "中文", [], true)
("邻居阿姨", "ICL_zh_female_linjuayi_tob", "中文", [], true)
("温柔小雅", "zh_female_wenrouxiaoya_moon_bigtts", "中文", [], true)
("天才童声", "zh_male_tiancaitongsheng_mars_bigtts", "中文", [], true)
("猴哥", "zh_male_sunwukong_mars_bigtts", "中文", [], true)
("熊二", "zh_male_xionger_mars_bigtts", "中文", [], true)
("佩奇猪", "zh_female_peiqi_mars_bigtts", "中文", [], true)
("武则天", "zh_female_wuzetian_mars_bigtts", "中文", [], true)
("顾姐", "zh_female_gujie_mars_bigtts", "中文", [], true)
("樱桃丸子", "zh_female_yingtaowanzi_mars_bigtts", "中文", [], true)
("广告解说", "zh_male_chunhui_mars_bigtts", "中文", [], true)
("少儿故事", "zh_female_shaoergushi_mars_bigtts", "中文", [], true)
("四郎", "zh_male_silang_mars_bigtts", "中文", [], true)
("俏皮女声", "zh_female_qiaopinvsheng_mars_bigtts", "中文", [], true)
("懒音绵宝", "zh_male_lanxiaoyang_mars_bigtts", "中文", [], true)
("亮嗓萌仔", "zh_male_dongmanhaimian_mars_bigtts", "中文", [], true)
("磁性解说男声/Morgan", "zh_male_jieshuonansheng_mars_bigtts", "中文,美式英语", [], true)
("鸡汤妹妹/Hope", "zh_female_jitangmeimei_mars_bigtts", "中文,美式英语", [], true)
("贴心女声/Candy", "zh_female_tiexinnvsheng_mars_bigtts", "中文,美式英语", [], true)
("萌丫头/Cutey", "zh_female_mengyatou_mars_bigtts", "中文,美式英语", [], true)
[/视频配音]

[有声阅读]
("内敛才俊", "ICL_zh_male_neiliancaijun_e991be511569_tob", "中文", [], true)
("温暖少年", "ICL_zh_male_yangyang_v1_tob", "中文", [], true)
("儒雅公子", "ICL_zh_male_flc_v1_tob", "中文", [], true)
("悬疑解说", "zh_male_changtianyi_mars_bigtts", "中文", [], true)
("儒雅青年", "zh_male_ruyaqingnian_mars_bigtts", "中文", [], true)
("霸气青叔", "zh_male_baqiqingshu_mars_bigtts", "中文", [], true)
("擎苍", "zh_male_qingcang_mars_bigtts", "中文", [], true)
("活力小哥", "zh_male_yangguangqingnian_mars_bigtts", "中文", [], true)
("古风少御", "zh_female_gufengshaoyu_mars_bigtts", "中文", [], true)
("温柔淑女", "zh_female_wenroushunv_mars_bigtts", "中文", [], true)
("反卷青年", "zh_male_fanjuanqingnian_mars_bigtts", "中文", [], true)
[/有声阅读]
"""